# Generated by Django 4.2.4 on 2023-09-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitle', models.CharField(blank=True, max_length=200, null=True)),
                ('cartype', models.CharField(blank=True, max_length=200, null=True)),
                ('carperkm', models.IntegerField(blank=True, null=True)),
                ('carcreated', models.DateTimeField(auto_now_add=True)),
                ('carfiyat', models.IntegerField(blank=True, null=True)),
                ('carimage', models.ImageField(blank=True, upload_to='media/cars')),
            ],
        ),
        migrations.CreateModel(
            name='Yolcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=200, null=True)),
                ('soy_isim', models.CharField(blank=True, max_length=200, null=True)),
                ('yas', models.IntegerField(blank=True, null=True)),
                ('tc', models.IntegerField(blank=True, null=True)),
                ('uyruk', models.CharField(blank=True, max_length=200, null=True)),
                ('cinsiyet', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Yolculuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yolcusayi', models.IntegerField(blank=True, null=True)),
                ('kac_km', models.IntegerField(blank=True, null=True)),
                ('nereden', models.CharField(blank=True, max_length=200, null=True)),
                ('nereye', models.CharField(blank=True, max_length=200, null=True)),
                ('cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.cars')),
            ],
        ),
        migrations.CreateModel(
            name='YolculuknYolcular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yolcular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.yolcular')),
                ('yolculuk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.yolculuk')),
            ],
        ),
    ]
