# Generated by Django 4.2.4 on 2023-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='carimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars'),
        ),
    ]
