# Generated by Django 4.2.4 on 2023-09-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0002_alter_cars_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekstra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uckopru', models.IntegerField(blank=True, null=True)),
                ('bebekkoltuk', models.IntegerField(blank=True, null=True)),
                ('yuksekkoltuk', models.IntegerField(blank=True, null=True)),
                ('onesaat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='yolculuk',
            name='ekstra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.ekstra'),
        ),
    ]
