# Generated by Django 4.2.4 on 2023-09-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0003_ekstra_yolculuk_ekstra'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolcular',
            name='yolculuk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.yolculuk'),
        ),
    ]
