# Generated by Django 4.2.4 on 2023-09-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0004_yolcular_yolculuk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolcular',
            name='yolculuk',
        ),
        migrations.RemoveField(
            model_name='yolculuk',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='yolculuk',
            name='ekstra',
        ),
        migrations.RemoveField(
            model_name='yolculuknyolcular',
            name='yolcular',
        ),
        migrations.RemoveField(
            model_name='yolculuknyolcular',
            name='yolculuk',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Ekstra',
        ),
        migrations.DeleteModel(
            name='Yolcular',
        ),
        migrations.DeleteModel(
            name='Yolculuk',
        ),
        migrations.DeleteModel(
            name='YolculuknYolcular',
        ),
    ]
