# Generated by Django 4.2.4 on 2023-09-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ozaydinapi', '0005_remove_yolcular_yolculuk_remove_yolculuk_cars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartitle', models.CharField(blank=True, max_length=150, null=True)),
                ('Cartype', models.CharField(blank=True, max_length=100, null=True)),
                ('Carfiyat', models.CharField(blank=True, max_length=100, null=True)),
                ('Carkm', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ekstra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kopru', models.IntegerField(blank=True, null=True)),
                ('Bebekkoltuk', models.IntegerField(blank=True, null=True)),
                ('Yuksekkoltuk', models.IntegerField(blank=True, null=True)),
                ('saatekstra', models.IntegerField(blank=True, null=True)),
                ('cars', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.cars')),
            ],
        ),
        migrations.CreateModel(
            name='NeredenNereye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nereden', models.CharField(blank=True, max_length=100, null=True)),
                ('Nereye', models.CharField(blank=True, max_length=50, null=True)),
                ('Yolcu', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YolcuBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=150, null=True)),
                ('soyisim', models.CharField(blank=True, max_length=150, null=True)),
                ('yas', models.IntegerField(blank=True, null=True)),
                ('uyruk', models.CharField(blank=True, max_length=100, null=True)),
                ('ekbilgi', models.CharField(blank=True, max_length=150, null=True)),
                ('ekstra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.ekstra')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='neredennereye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.neredennereye'),
        ),
    ]
