# Generated by Django 4.2.4 on 2023-09-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0007_alter_cars_carkm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='neredennereye',
        ),
        migrations.RemoveField(
            model_name='ekstra',
            name='cars',
        ),
        migrations.AddField(
            model_name='neredennereye',
            name='cars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.cars'),
        ),
        migrations.AddField(
            model_name='yolcubilgi',
            name='NeredenNereye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.neredennereye'),
        ),
    ]
