# Generated by Django 4.2.4 on 2023-09-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0008_remove_cars_neredennereye_remove_ekstra_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neredennereye',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='yolcubilgi',
            name='ekstra',
        ),
        migrations.CreateModel(
            name='YolcuLast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.cars')),
                ('ekstra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.ekstra')),
                ('neredennereye', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.neredennereye')),
                ('yolcubilgi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.yolcubilgi')),
            ],
        ),
    ]
