# Generated by Django 4.2.4 on 2023-09-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0009_remove_neredennereye_cars_remove_yolcubilgi_ekstra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolcubilgi',
            name='NeredenNereye',
        ),
    ]
