# Generated by Django 4.2.4 on 2023-09-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozaydinapi', '0010_remove_yolcubilgi_neredennereye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolculast',
            name='car',
        ),
        migrations.RemoveField(
            model_name='yolculast',
            name='ekstra',
        ),
        migrations.AddField(
            model_name='neredennereye',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.cars'),
        ),
        migrations.AddField(
            model_name='yolcubilgi',
            name='ekstra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ozaydinapi.ekstra'),
        ),
    ]
